GittiBu.Web/Areas/AdminPanel/Controllers/AdvertCategoriesController.cs
using System.Threading.Tasks;
using GittiBu.Common;
using GittiBu.Models;
using GittiBu.Services;
using GittiBu.Web.Areas.AdminPanel.Models;
using Microsoft.AspNetCore.Mvc;

namespace GittiBu.Web.Areas.AdminPanel.Controllers
{
    public class AdvertCategoriesController : AdminBaseController
    {
        // GET
        public IActionResult Index()
        {
            using (var service = new AdvertCategoryService())
            {
                var categories = service.GetAllCategories();
                return View(categories);
            }
        }

        public IActionResult Edit(int id)
        {
            var model = new AdvertCategoryEditViewModel();
            using (var service = new AdvertCategoryService())
            {
                var category = service.Get(id);
                
                if (category == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Kategori bulunamadı");
                    return RedirectToAction("Index");
                }
                var categoryEn = service.Get(id, 2);
               
               
                    model.CategoryTr = category;
                    model.CategoryEn = categoryEn;
               
                var categories = service.GetAllCategories();
                ViewBag.Categories = categories;
               
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> SaveEdit(AdvertCategoryPostModel model)
        {
            using (var contentService = new TextService())
            using (var service=new AdvertCategoryService())
            {
                var category = service.Get(model.ID);
                if (category == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "İlan kategorisi bulunamadı.");
                    return RedirectToAction("Index");
                }
                if (category.ParentCategoryID != model.ParentCategoryID)
                {
                    category.ParentCategoryID = model.ParentCategoryID;
                    var update = service.Update(category);
                    if (!update)
                    {
                        AdminNotification = new UiMessage(NotyType.error, "İlan kategorisi güncellenemedi.");
                        return RedirectToAction("Edit", new {id = model.ID});
                    }
                }

                if (model.File != null)
                {
                    var fileName = model.SlugTr + System.IO.Path.GetExtension(model.File.FileName);
                    var filePath = new FileService().FileUpload(GetLoginID(),model.File, "/Upload/Categories/", fileName);
                    category.IconSource = filePath;
                    var update = service.Update(category);
                    if (!update)
                    {
                        AdminNotification = new UiMessage(NotyType.error, "Kategori görseli güncellenemedi.");
                        return RedirectToAction("Edit", new {id = model.ID});
                    }
                }
                category.Order = model.Order;
                category.MaxInstallment = model.MaxInstallment;
                service.Update(category);
                
                /* Türkçe Güncellemeler */
                contentService.Update(category.NameID, model.NameTr, 1);
                contentService.Update(category.DescriptionID, model.DescriptionTr, 1);
                contentService.Update(category.SeoDescriptionID, model.SeoDescriptionTr, 1);
                contentService.Update(category.SeoKeywordsID, model.SeoKeywordsTr, 1);
                contentService.Update(category.SlugID, model.SlugTr, 1);
                
                /* İngilizce Güncellemeler */
                contentService.Update(category.NameID, model.NameEn, 2);
                contentService.Update(category.DescriptionID, model.DescriptionEn, 2);
                contentService.Update(category.SeoDescriptionID, model.SeoDescriptionEn, 2);
                contentService.Update(category.SeoKeywordsID, model.SeoKeywordsEn, 2);
                contentService.Update(category.SlugID, model.SlugEn, 2);
                
                AdminNotification = new UiMessage(NotyType.success, "İlan kategorisi güncellendi.");
                return RedirectToAction("Index");
            }
        }

        public IActionResult Create()
        {
            var categories = new System.Collections.Generic.List<AdvertCategory>();
            using (var service = new AdvertCategoryService())
            {
                 categories = service.GetAll();
                
            }
            return View(categories);
        }
        [HttpPost]
        public async Task<IActionResult> Create(AdvertCategoryPostModel model)
        {
            using (var fileService = new FileService())
            using (var contentService = new TextService())
            using (var service=new AdvertCategoryService())
            {
                var category = new AdvertCategory
                {
                    ParentCategoryID = model.ParentCategoryID,
                    Order = model.Order,
                    IsActive = model.IsActive,
                    MaxInstallment = model.MaxInstallment
                };

                var contentKey = contentService.GetNextKey();
                category.NameID = contentKey;
                contentKey++;
                category.DescriptionID = contentKey;
                contentKey++;
                category.SeoDescriptionID = contentKey;
                contentKey++;
                category.SeoKeywordsID = contentKey;
                contentKey++;
                category.SlugID = contentKey;

                contentService.Insert(category.NameID, model.NameTr, model.NameEn);
                contentService.Insert(category.DescriptionID, model.DescriptionTr, model.DescriptionEn);
                contentService.Insert(category.SeoDescriptionID, model.SeoDescriptionTr, model.SeoDescriptionEn);
                contentService.Insert(category.SeoKeywordsID, model.SeoKeywordsTr, model.SeoKeywordsEn);
                contentService.Insert(category.SlugID, model.SlugTr, model.SlugEn);
                
                var insert = service.Insert(category);
                if (!insert)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Kategori kayıt edilemedi.");
                    return RedirectToAction("Create");
                }
                if (model.File != null)
                {
                    var fileName = model.SlugTr + System.IO.Path.GetExtension(model.File.FileName);
                    var filePath = fileService.FileUpload(GetLoginID(),model.File, "/Upload/Categories/", fileName);
                    category.IconSource = filePath;
                    var update = service.Update(category);
                    if (!update)
                    {
                        AdminNotification = new UiMessage(NotyType.error, "Kategori görseli kayıt edilemedi.");
                        return RedirectToAction("Edit", new {id = model.ID});
                    }
                }
                
                AdminNotification = new UiMessage(NotyType.success, "İlan kategorisi eklendi.");
               
            }
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public JsonResult UpdateStatus(int id, bool status)
        {
            using (var service = new AdvertCategoryService())
            {
                var category = service.Get(id);
                if (category == null)
                {
                    return Json(new {isSuccess = false, message = "Kategori bulunamadı"});
                }

                category.IsActive = status;
                var update = service.Update(category);
                if (!update)
                    return Json(new {isSuccess = false, message = "Güncelleme başarısız"});
                
                return Json(new {isSuccess = true, message = "İlan kategorisi aktiflik durumu güncellendi."});
            }
        }
    }
}

GittiBu.Web/Areas/AdminPanel/Views/AdvertCategories/Create.cshtml
@model List<AdvertCategory>
@{
    ViewBag.Title = "İlan Kategorisi Ekle";
    Layout = "AdminLayout";
    ViewData["ActiveMenu"] = "menu-item-ad-categories";
}



<div class="m-portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon m--hide">
                    <i class="la la-gear"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Kategori Ekle
                </h3>
            </div>
        </div>
    </div>

    
    @using(Html.BeginForm("Create", "AdvertCategories", FormMethod.Post, 
        new { enctype = "multipart/form-data", @class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" }))
    {
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Üst Kategori:</label>
                <div class="col-lg-3">
                    <select name="ParentCategoryID" class="form-control">
                        <option value="0">Yok</option>
                        @foreach (var category in Model)
                        {
                            <option value="@category.ID">@category.Name</option>
                        }
                    </select>
                </div>
                <label class="col-lg-2 col-form-label">Icon:</label>
                <div class="col-lg-3">
                    <input type="file" name="File" class="form-control"/>
                </div>
            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Sırama:</label>
                <div class="col-lg-3">
                    <input type="number" name="Order" class="form-control" value="0" required/>
                </div>
                <label class="col-lg-2 col-form-label">Max. Taksit Seçeneği:</label>
                <div class="col-lg-3">
                    <input type="number" name="MaxInstallment" class="form-control" value="1" required/>
                </div>
            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label"></label>
                <div class="col-lg-3">
                    <label class="m-checkbox m-checkbox--state-success">
                        <input type="checkbox" name="IsActive" value="false"> Aktif
                        <span></span>
                    </label>
                </div>
            </div>
        </div>
        
        <div class="m-divider">
            <span></span>
            <span>Türkçe İçerik</span>
            <span></span>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Ad:</label>
                <div class="col-lg-3">
                    <input type="text" class="form-control m-input" name="NameTr" required>
                </div>
                <label class="col-lg-2 col-form-label">Açıklama:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="DescriptionTr" rows="3" required></textarea>
                </div>
                
            </div>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">[SEO] Açıklama:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="SeoDescriptionTr" rows="3" required></textarea>
                </div>
                <label class="col-lg-2 col-form-label">[SEO] Keywords:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="SeoKeywordsTr" rows="3" required></textarea>
                </div>
            </div>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">[SEO] URL Yapısı:</label>
                <div class="col-lg-3">
                    <input type="text" class="form-control m-input" name="SlugTr" required>
                </div>
            </div>
        </div>
        
        <div class="m-divider">
            <span></span>
            <span>İngilizce İçerik</span>
            <span></span>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Ad:</label>
                <div class="col-lg-3">
                    <input type="text" class="form-control m-input" name="NameEn" required>
                </div>
                <label class="col-lg-2 col-form-label">Açıklama:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="DescriptionEn" rows="3" required></textarea>
                </div>
            </div>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">[SEO] Açıklama:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="SeoDescriptionEn" rows="3" required></textarea>
                </div>
                <label class="col-lg-2 col-form-label">[SEO] Keywords:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="SeoKeywordsEn" rows="3" required></textarea>
                </div>
            </div>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">[SEO] URL Yapısı:</label>
                <div class="col-lg-3">
                    <input type="text" class="form-control m-input" name="SlugEn" required>
                </div>
            </div>
        </div>
        
        
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-10">
                        <button type="submit" class="btn btn-success">Kaydet</button>
                        <a href="/AdminPanel/AdvertCategories" class="btn btn-secondary">Vazgeç</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

GittiBu.Web/Areas/AdminPanel/Views/AdvertCategories/Edit.cshtml
@model AdvertCategoryEditViewModel

@{
    ViewBag.Title = "İlan Kategorisi Düzenle";
    Layout = "AdminLayout";
    ViewData["ActiveMenu"] = "menu-item-ad-categories";
}


<div class="m-portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon m--hide">
                    <i class="la la-gear"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    #@Model.CategoryTr.ID | @Model.CategoryTr.Name
                </h3>
            </div>
        </div>
    </div>

    
    @using(Html.BeginForm("SaveEdit", "AdvertCategories", FormMethod.Post, 
        new { @class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed", enctype = "multipart/form-data" }))
    {
        <input type="hidden" name="ID" value="@Model.CategoryTr.ID"/>
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Üst Kategori:</label>
                <div class="col-lg-3">
                    <select name="ParentCategoryID" class="form-control">
                        <option value="0">Yok</option>
                        @foreach (var category in (List<AdvertCategory>) ViewBag.Categories)
                        {
                            <option value="@category.ID">@category.Name</option>
                        }
                    </select>
                </div>
                <label class="col-lg-2 col-form-label">Icon:</label>
                <div class="col-lg-3">
                    <input type="file" name="File" class="form-control"/>
                </div>
            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Sırama:</label>
                <div class="col-lg-3">
                    <input type="number" name="Order" class="form-control" value="@Model.CategoryTr.Order" required/>
                </div>
                <label class="col-lg-2 col-form-label">Max. Taksit Seçeneği:</label>
                <div class="col-lg-3">
                    <input type="number" name="MaxInstallment" class="form-control" value="@Model.CategoryTr.MaxInstallment" required/>
                </div>
            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label"></label>
                <div class="col-lg-3">
                    <label class="m-checkbox m-checkbox--state-success">
                        <input type="checkbox" name="IsActive" value="@Model.CategoryTr.IsActive.ToString().ToLower()" @(Model.CategoryTr.IsActive?"checked":null)> Aktif
                        <span></span>
                    </label>
                </div>
            </div>
        </div>
        
        <div class="m-divider">
            <span></span>
            <span>Türkçe İçerik</span>
            <span></span>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Ad:</label>
                <div class="col-lg-3">
                    <input type="text" class="form-control m-input" value="@Model.CategoryTr.Name" name="NameTr">
                </div>
                <label class="col-lg-2 col-form-label">Açıklama:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="DescriptionTr" rows="3">@Model.CategoryTr.Description</textarea>
                </div>
                
            </div>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">[SEO] Açıklama:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="SeoDescriptionTr" rows="3">@Model.CategoryTr.SeoDescription</textarea>
                </div>
                <label class="col-lg-2 col-form-label">[SEO] Keywords:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="SeoKeywordsTr" rows="3">@Model.CategoryTr.SeoKeywords</textarea>
                </div>
            </div>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">[SEO] URL Yapısı:</label>
                <div class="col-lg-3">
                    <input type="text" class="form-control m-input" name="SlugTr" value="@Model.CategoryTr.Slug">
                </div>
            </div>
        </div>
        
        <div class="m-divider">
            <span></span>
            <span>İngilizce İçerik</span>
            <span></span>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Ad:</label>
                <div class="col-lg-3">
                    <input type="text" class="form-control m-input" value="@Model.CategoryEn.Name" name="NameEn">
                </div>
                <label class="col-lg-2 col-form-label">Açıklama:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="DescriptionEn" rows="3">@Model.CategoryEn.Description</textarea>
                </div>
            </div>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">[SEO] Açıklama:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="SeoDescriptionEn" rows="3">@Model.CategoryEn.SeoDescription</textarea>
                </div>
                <label class="col-lg-2 col-form-label">[SEO] Keywords:</label>
                <div class="col-lg-3">
                    <textarea class="form-control m-input" name="SeoKeywordsEn" rows="3">@Model.CategoryEn.SeoKeywords</textarea>
                </div>
            </div>
        </div>
        
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">[SEO] URL Yapısı:</label>
                <div class="col-lg-3">
                    <input type="text" class="form-control m-input" name="SlugEn" value="@Model.CategoryEn.Slug">
                </div>
            </div>
        </div>
        
        
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-10">
                        <button type="submit" class="btn btn-success">Kaydet</button>
                        <a href="/AdminPanel/AdvertCategories" class="btn btn-secondary">Vazgeç</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts{
    <script>
        $('select[name="ParentCategoryID"]').val(@(Model.CategoryTr.ParentCategoryID));
    </script>
}

GittiBu.Web/Areas/AdminPanel/Views/AdvertCategories/Index.cshtml
@model List<AdvertCategory>

@{
    ViewBag.Title = "İlan Kategorileri";
    ViewData["ActiveMenu"] = "menu-item-ad-categories";
}

@section Styles{
    <link href="/AdminContent/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css">
}

<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    İlan Kategorileri
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="/AdminPanel/AdvertCategories/Create" class="btn btn-primary m-btn m-btn--pill m-btn--custom m-btn--icon m-btn--air">
                        <span>
                            <i class="la la-plus"></i>
                            <span>Yeni Kategori</span>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="table-responsive">
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Adı</th>
                    <th>SEO URL</th>
                    <th>Üst Kategori</th>
                    <th>Aktif</th>
                    <th>İşlemler</th>
                </tr>
                </thead>
                <tbody>

                @foreach (var category in Model)
                {
                    <tr id="row_@category.ID">
                        <td> @category.ID</td>
                        <td> @category.Name </td>
                        <td> @category.Slug </td>
                        <td> @(category.ParentCategory?.Name) </td>
                        <td id="status_@category.ID"> @(category.IsActive ? "Aktif" : "Pasif") </td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group">
                                <a href="/AdminPanel/AdvertCategories/Edit/@category.ID" class="m-btn btn btn-info" title="Güncelle">
                                    <i class="la la-pencil-square"></i>
                                </a>
                                @if (category.IsActive)
                                {
                                    <button onclick="updateStatusMessage(@category.ID, false, '@category.Name')" class="m-btn btn btn-warning" title="Pasifleştir">
                                        <i class="la la-close"></i>
                                    </button>
                                }
                                else
                                {
                                    <button onclick="updateStatusMessage(@category.ID, true, '@category.Name')" class="m-btn btn btn-success" title="Aktifleştir">
                                        <i class="la la-check"></i>
                                    </button>
                                }
                            </div>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
        
    </div>
</div>


@section Scripts{
    <script src="/AdminContent/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script>
        $("#m_table_1").DataTable({
            order: [0, 'desc'],
            dom: "<'row'<'col-sm-6 text-left'f><'col-sm-6 text-right'B>>\n\t\t\t<'row'<'col-sm-12'tr>>\n\t\t\t<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7 dataTables_pager'lp>>",
            buttons: ["print", "copyHtml5", "excelHtml5", "csvHtml5", "pdfHtml5"]
        });
    </script>
    <script>
        function updateStatusMessage(id, isActive, title) {
            var status = isActive ? "aktifleştirmek" : "pasifleştirmek";
            
            Swal({
                title: '#'+id+' '+title+' başlıklı kategoriyi '+status+' istediğinize emin misiniz?',
                text: "Kategori güncellenmek üzere",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Evet',
                cancelButtonText: 'Vazgeç'
            }).then((result) => {
                if (result.value) {
                    updateStatus(id, isActive);
                }
            });
        }
        function updateStatus(id, status) {
            var newStatus = status ? "Aktif" : "Pasif";
            $.ajax({
                url: "/AdminPanel/AdvertCategories/UpdateStatus",
                type: "POST",
                data: { id, status },
                success: function(data) {
                    if (data.isSuccess) {
                        $('#status_' + id).html(newStatus);
                        notify("success", data.message);
                    } else {
                        notify("danger", data.message);
                    }
                }
            });
        }
    </script>
}