GittiBu.Web/Areas/AdminPanel/Controllers/BannersController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using GittiBu.Common;
using GittiBu.Models;
using GittiBu.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GittiBu.Web.Areas.AdminPanel.Controllers
{
    public class BannersController : AdminBaseController
    {
        public IActionResult Index()
        {
            using (var service = new BannerService())
            {
                var list = service.GetAllBanners();
                return View(list);
            }
        }

        public IActionResult Create()
        {
            using (var userService = new UserService())
            {
                var users = userService.GetAll();
                return View(users);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Create(Banner banner)
        {
            if (banner == null)
            {
                AdminNotification = new UiMessage(NotyType.error, "Banner geçersiz");
                return Redirect("Create");
            }
            if (banner.ImageSourceFile == null)
            {
                AdminNotification = new UiMessage(NotyType.error, "Görsel geçersiz");
                return Redirect("Create");
            }
            using (var service = new BannerService())
            {
                var fileName = "banner_" + new Random().Next(100, 1000) + Path.GetExtension(banner.ImageSourceFile.FileName);
                var filePath = new FileService().FileUpload(GetLoginID(),banner.ImageSourceFile, "/Upload/Dopings/", fileName);
                banner.ImageSource = filePath;
                banner.CreatedDate = DateTime.Now;
                var insert = service.Insert(banner);
                if (!insert)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner girişi başarısız");
                    return Redirect("Create");
                }
                AdminNotification = new UiMessage(NotyType.success, "Banner girişi yapıldı.");
                return Redirect("Index");
            }
        }

        #region Details

        public IActionResult Details(int id)
        {
            using (var service = new BannerService())
            {
                var banner = service.GetWithUser(id);
                if (banner == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner bulunamadı");
                    return RedirectToAction("Index");
                }
                return View(banner);
            }
        }

        [HttpPost]
        public IActionResult UpdateEndDate(int id, DateTime endDate)
        {
            using (var service = new BannerService())
            {
                var banner = service.Get(id);
                if (banner == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner bulunamadı");
                    return RedirectToAction("Index");
                }
                banner.EndDate = endDate;
                var update = service.Update(banner);
                AdminNotification = update ? new UiMessage(NotyType.success, "Banner bitiş tarihi güncellendi.") : new UiMessage(NotyType.error, "Banner tarihi güncellemesi başarısız.");
                return RedirectToAction("Details", new { id });
            }
        }

        public async Task<IActionResult> UpdateFile(int id, IFormFile file)
        {
            using (var service = new BannerService())
            {
                var banner = service.Get(id);
                if (banner == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner bulunamadı");
                    return RedirectToAction("Index");
                }
                if (file == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Görsel tespit edilemedi.");
                    return RedirectToAction("Details", new { id });
                }
                var fileName = "banner_" + id + "_" + new Random().Next(100) + Path.GetExtension(file.FileName);
                var filePath = new FileService().FileUpload(GetLoginID(),file, "/Upload/Dopings/", fileName);
                banner.ImageSource = filePath;
                var update = service.Update(banner);
                if (!update)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner görseli güncellenemedi.");
                    return RedirectToAction("Details", new { id });
                }
                AdminNotification = new UiMessage(NotyType.success, "Banner görseli güncellendi.");

            }
            return RedirectToAction("Details", new { id });
        }
        [HttpPost]
        public IActionResult UpdateTitle(int id, string title)
        {
            using (var service = new BannerService())
            {
                var banner = service.Get(id);
                if (banner == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner bulunamadı");
                    return RedirectToAction("Details", new { id });
                }

                if (string.IsNullOrEmpty(title))
                {
                    AdminNotification = new UiMessage(NotyType.error, "Başlık geçersiz");
                    return RedirectToAction("Details", new { id });
                }

                banner.Title = title;
                var update = service.Update(banner);
                if (!update)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner güncellenemedi");
                    return RedirectToAction("Details", new { id });
                }

                AdminNotification = new UiMessage(NotyType.success, "Banner güncellendi");
                return RedirectToAction("Details", new { id });
            }
        }

        [HttpPost]
        public IActionResult UpdateUrl(int id, string url)
        {
            using (var service = new BannerService())
            {
                var banner = service.Get(id);
                if (banner == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner bulunamadı");
                    return RedirectToAction("Details", new { id });
                }

                if (string.IsNullOrEmpty(url))
                {
                    AdminNotification = new UiMessage(NotyType.error, "URL geçersiz");
                    return RedirectToAction("Details", new { id });
                }

                banner.Url = url;
                var update = service.Update(banner);
                if (!update)
                {
                    AdminNotification = new UiMessage(NotyType.error, "URL güncellenemedi");
                    return RedirectToAction("Details", new { id });
                }

                AdminNotification = new UiMessage(NotyType.success, "URL güncellendi");
                return RedirectToAction("Details", new { id });
            }
        }

        [HttpPost]
        public IActionResult UpdateType(int id, Enums.BannerType type)
        {
            using (var service = new BannerService())
            {
                var banner = service.Get(id);
                if (banner == null)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner bulunamadı");
                    return RedirectToAction("Details", new { id });
                }
                banner.TypeID = type;
                var update = service.Update(banner);
                if (!update)
                {
                    AdminNotification = new UiMessage(NotyType.error, "Banner güncellenemedi");
                    return RedirectToAction("Details", new { id });
                }

                AdminNotification = new UiMessage(NotyType.success, "Banner güncellendi");
                return RedirectToAction("Details", new { id });
            }
        }
        #endregion

        [HttpPost]
        public JsonResult UpdateStatus(int id, bool status)
        {
            using (var service = new BannerService())
            {
                var banner = service.Get(id);
                if (banner == null)
                {
                    return Json(new { isSuccess = false, message = "Banner bulunamadı" });
                }

                banner.IsActive = status;
                var update = service.Update(banner);
                if (!update)
                    return Json(new { isSuccess = false, message = "Güncelleme başarısız" });

                return Json(new { isSuccess = true, message = "Banner aktiflik durumu güncellendi." });
            }
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            using (var service = new BannerService())
            {
                var banner = service.Get(id);

                var delete = service.Delete(id);
                if (!delete)
                    return Json(new { isSuccess = false, message = "Silme işlemi başarısız" });

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot" + banner.ImageSource);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
                return Json(new { isSuccess = true, message = "Banner silindi." });
            }
        }


    }
}

GittiBu.Web/Areas/AdminPanel/Views/Banners/Create.cshtml
@model List<User>

@{
    ViewBag.Title = "Banner Girişi";
    Layout = "AdminLayout";
    ViewData["ActiveMenu"] = "menu-item-banners";
}


<div class="row">
    <div class="col-lg-6">
        <!--begin::Portlet-->
        <div class="m-portlet">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
						</span>
                        <h3 class="m-portlet__head-text">
							Banner Girişi
						</h3>
                    </div>
                </div>
            </div>
            <!--begin::Form-->
            @using (Html.BeginForm("Create", "Banners", FormMethod.Post, 
                new { @class="m-form", enctype = "multipart/form-data" }))
            {
                <div class="m-portlet__body">
                    <div class="m-form__section m-form__section--first">
                        <div class="form-group m-form__group">
                            <label>Kullanıcı</label>
                            <select class="form-control select2" name="UserID" required>
                                @foreach (var user in Model.OrderBy(d=>d.Name))
                                {
                                    <option value="@user.ID">#@user.ID @user.Name (@user.UserName)</option>
                                }
                            </select>
                        </div>
                        <div class="form-group m-form__group">
                            <label>Başlık</label>
                            <input type="text" class="form-control m-input" name="Title">
                        </div>
                        
                        <div class="form-group m-form__group row">
                            <div class="col-lg-6">
                                <label>URL</label>
                                <input type="text" name="Url" class="form-control" required/>
                            </div>
                            <div class="col-lg-6">
                                <label>Başlangıç Tarihi</label>
                                <input type="date" name="StartDate" class="form-control" required/>
                            </div>
                        </div>
                        
                        <div class="form-group m-form__group row">
                            <div class="col-lg-6">
                                <label>Bitiş Tarihi</label>
                                <input type="date" name="EndDate" class="form-control" required/>
                            </div>
                            <div class="col-lg-6">
                                <label>Banner Tipi</label>
                                <select class="form-control" name="TypeID" required>
                                    <option value="@(Enums.BannerType.Logo)">Logo Banner</option>
                                    <option value="@(Enums.BannerType.Banner)">İlan Ayırıcı Banner</option>
                                    <option value="@(Enums.BannerType.Slider)">Slider</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group m-form__group row">
                            <div class="col-lg-6">
                                <label>Ücret</label>
                                <input type="number" name="Price" class="form-control" />
                            </div>
                            <div class="col-lg-6">
                                <label>Görsel</label>
                                <input type="file" name="ImageSourceFile" class="form-control" required/>
                            </div>
                        </div>
                        
                        <div class="m-form__group form-group">
                            <label class="m-checkbox m-checkbox--state-success">
                                <input type="checkbox" name="IsActive" value="false"> Aktif
                                <span></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            }
            <!--end::Form-->
        </div>
        <!--end::Portlet-->

        <!--begin::Portlet-->

        <!--end::Portlet-->
    </div>

</div>


@section Scripts{
    <script>
        $(".select2").select2({placeholder:"Seçiniz"})
    </script>
}

GittiBu.Web/Areas/AdminPanel/Views/Banners/Details.cshtml
@model Banner

@{
    ViewBag.Title = "Banner Detayları";
    Layout = "AdminLayout";
    ViewData["ActiveMenu"] = "menu-item-banners";
}


<div class="m-content">
        
    <div class="row">
    <div class="col-xl-6">
        <div class="row">
            <div class="col-12">
                <div class="m-portlet m-portlet--full-height ">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text">
                                    Banner Detayları
                                </h3>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__body">
                        <div class="m-widget12">
                            <div class="m-widget12__item">
                                <span class="m-widget12__text1" style="width: 100%">Başlık<br><span>@Model.Title</span></span>
                            </div>
                            <div class="m-widget12__item">
                                <span class="m-widget12__text1">Kategori<br><span>@Model.TypeID</span></span>
                                <span class="m-widget12__text1">Tıklanma Miktarı<br>
                                    <span>
                                        <i class="la la-mouse-pointer"></i> @Model.ClickCount</span>
                                </span>
                            </div>
                            <div class="m-widget12__item">
                                <span class="m-widget12__text1">Oluşturulma Tarihi<br><span>@Model.CreatedDate.ToString("g")</span></span>
                                <span class="m-widget12__text1">Bitiş Tarihi<br><span>@(Model.EndDate?.ToString("g"))</span></span>
                            </div>
                            <div class="m-widget12__item">
                                <span class="m-widget12__text1">Aktif<br><span>@(Model.IsActive ? "Evet" : "Hayır")</span></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-xl-6">
        <div class="row">
            <div class="col-12">
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide"><i class="la la-gear"></i></span>
                                <h3 class="m-portlet__head-text">Güncellemeler</h3>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__body">
                        @using (Html.BeginForm("UpdateEndDate", "Banners", FormMethod.Post))
                        {
                            <input type="hidden" name="id" value="@Model.ID"/>
                            <div class="form-group m-form__group row">
                                <label class="col-lg-2 col-form-label">Bitiş Tarihi:</label>
                                <div class="col-lg-6">
                                    <input type="date" class="form-control m-input" name="EndDate" required>
                                </div>
                                <div class="col-lg-2">
                                    <button type="submit" class="btn btn-success">Güncelle</button>
                                </div>
                            </div>
                        }
                        @using (Html.BeginForm("UpdateTitle", "Banners", FormMethod.Post))
                        {
                            <input type="hidden" name="id" value="@Model.ID"/>
                            <div class="form-group m-form__group row">
                                <label class="col-lg-2 col-form-label">Başlık:</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control m-input" name="Title" required>
                                </div>
                                <div class="col-lg-2">
                                    <button type="submit" class="btn btn-success">Güncelle</button>
                                </div>
                            </div>
                        }
                        @using (Html.BeginForm("UpdateType", "Banners", FormMethod.Post))
                        {
                            <input type="hidden" name="id" value="@Model.ID"/>
                            <div class="form-group m-form__group row">
                                <label class="col-lg-2 col-form-label">Kategori:</label>
                                <div class="col-lg-6">
                                    <select class="form-control" name="Type" required>
                                        <option value="@(Enums.BannerType.Logo)">Logo Banner</option>
                                        <option value="@(Enums.BannerType.Banner)">İlan Ayırıcı Banner</option>
                                        <option value="@(Enums.BannerType.Slider)">Slider</option>
                                    </select>
                                </div>
                                <div class="col-lg-2">
                                    <button type="submit" class="btn btn-success">Güncelle</button>
                                </div>
                            </div>
                        }
                        
                        @using (Html.BeginForm("UpdateFile", "Banners", FormMethod.Post, 
                            new { enctype = "multipart/form-data" }))
                        {
                            <input type="hidden" name="id" value="@Model.ID"/>
                            <div class="form-group m-form__group row">
                                <label class="col-lg-2 col-form-label">Banner Görseli:</label>
                                <div class="col-lg-6">
                                    <input type="file" class="form-control m-input" name="file" required>
                                </div>
                                <div class="col-lg-2">
                                    <button type="submit" class="btn btn-success">Güncelle</button>
                                </div>
                            </div>
                        }
                        @using (Html.BeginForm("UpdateUrl", "Banners", FormMethod.Post))
                        {
                            <input type="hidden" name="id" value="@Model.ID"/>
                            <div class="form-group m-form__group row">
                                <label class="col-lg-2 col-form-label">URL:</label>
                                <div class="col-lg-6">
                                    <input type="url" class="form-control m-input" name="url" value="@Model.Url" required>
                                </div>
                                <div class="col-lg-2">
                                    <button type="submit" class="btn btn-success">Güncelle</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row">
            <div class="col-12">
                <div class="m-portlet m-portlet--full-height ">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text">
                                    Kullanıcı Bilgileri
                                </h3>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__body">
                        <div class="m-widget13">
                            <div class="m-widget13__item">
                                <span class="m-widget13__desc m--align-right">
                                    Kullanıcı
                                </span>
                                <span class="m-widget13__text m-widget13__text-bolder">
                                    @Model.User.Name
                                </span>
                            </div>
                            <div class="m-widget13__item">
                                <span class="m-widget13__desc m--align-right">
                                    Kullanıcı Adı:
                                </span>
                                <span class="m-widget13__text m-widget13__text-bolder">
                                    @Model.User.UserName
                                </span>
                            </div>
                            <div class="m-widget13__item">
                                <span class="m-widget13__desc m--align-right">
                                    E-mail:
                                </span>
                                <span class="m-widget13__text">
                                    <a href="mailto:@Model.User.Email">@Model.User.Email</a>
                                </span>
                            </div>
                            <div class="m-widget13__item">
                                <span class="m-widget13__desc m--align-right">
                                    Telefon:
                                </span>
                                <span class="m-widget13__text m-widget13__text-bolder">
                                    <a href="tel:@Model.User.MobilePhone">@Model.User.MobilePhone</a>
                                </span>
                            </div>
                            <div class="m-widget13__item">
                                <span class="m-widget13__desc m--align-right">
                                    Üyelik Tarihi:
                                </span>
                                <span class="m-widget13__text">
                                    @Model.User.CreatedDate?.ToString("g")
                                </span>
                            </div>
                            <div class="m-widget13__item">
                                <span class="m-widget13__desc m--align-right">
                                    Hakkında:
                                </span>
                                <span class="m-widget13__text m-widget13__number-bolder m--font-brand">
                                    @Model.User.About
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-12">
                <div class="m-portlet m-portlet--bordered-semi m-portlet--full-height ">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text">
                                    Banner Görseli
                                </h3>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__body">
                        <div class="row">
                            <a href="@Model.ImageSource" target="_blank">
                            <img src="@Model.ImageSource" width="100%" style="max-height: 200px"/>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
    </div>

</div>

@section Scripts
{
    <script>
        function deleteImage(id) {
            Swal({
                title: 'Yazı Görseli Silinecek',
                text: "Yazı görselini silmek istediğinize emin misiniz?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Evet, Sil!',
                cancelButtonText: 'Vazgeç'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "/AdminPanel/BlogPosts/DeleteImage",
                        data: {id},
                        type: "POST",
                        success: function(data) {
                            if (data.isSuccess) {
                                $('#image_' + id).remove();
                                notify("success", data.message);
                            } else {
                                notify("danger", data.message);
                            }
                        }
                    });
                }
            });
        }
    </script>
}